
POST  http://localhost:3000/api/reclamation
Content-Type: application/json
"x-auth-token"="1234567"

{
        "categorie": "Piscine",
        "images":[
                "image1",
                "image2"
        ],
        "commentaire": "I have a problem please Help me",
        "status": "Pending"
}






